---
- hosts: all
  become: yes
  gather_facts: yes
  vars:
    regex: '[^A-Za-z0-9._-]'
    replace: '_'

  roles:
    - docker

  tasks:
  - name: Ensure vars are loaded
    ansible.builtin.include_vars:
      dir: vars/custom

  - name: Ensure HMS-Docker role
    ansible.builtin.import_role:
      name: hmsdocker

  - name: Verify all Traefik endpoints are accessible
    ansible.builtin.uri:
      url: http://{{ item.key }}.{{ hms_docker_domain }}
      status_code: 200,302,401,403
      validate_certs: no
    with_dict:
      - "{{ hms_docker_container_map }}"
    when:
      - item.value.traefik is defined and item.value.traefik
      - item.value.enabled is defined and item.value.enabled
      - container_enabled_traefik
      - traefik_verify_endpoints is defined and traefik_verify_endpoints
