# The container map, use this to disable specific containers from running or being accessible by Traefik
# Values:
#  `enabled`: Enables or disables the container
#  `proxy_host_rules`: Sets the host rules for the container (so you can access the container via "http://<host>.<domain>")
#  `directory`: Creates the container directory within the apps folder
#  `traefik`: Enables or disables accessing the container via Traefik
#  `expose_to_public`: Enables or disables exposing the container to the public internet via Traefik (removes allowlist restrictions, does not expose the container port)
hms_docker_container_map:
  traefik:
    enabled: yes
    proxy_host_rule: traefik
    directory: yes
    traefik: yes
  sonarr:
    enabled: yes
    proxy_host_rule: sonarr
    directory: yes
    traefik: yes
    expose_to_public: yes
    homepage: yes
    homepage_stats: yes
  radarr:
    enabled: yes
    proxy_host_rule: radarr
    directory: yes
    traefik: yes
    expose_to_public: yes
    homepage: yes
    homepage_stats: yes
  portainer:
    enabled: yes
    proxy_host_rule: portainer
    directory: yes
    traefik: yes
    expose_to_public: yes
    homepage: yes
    homepage_stats: yes
  prowlarr:
    enabled: yes
    proxy_host_rule: prowlarr
    directory: yes
    traefik: yes
    expose_to_public: yes
    homepage: yes
    homepage_stats: yes
  homepage:
    enabled: yes
    proxy_host_rule: homepage
    directory: yes
    traefik: yes
    expose_to_public: yes
    homepage: yes
    homepage_stats: yes
