### Container settings
# The "state" of all containers // default: "present" // valid: "present" // "absent"
hms_docker_compose_container_state: present

# Controls how the containers are restarted upon server or docker restart // default: "unless-stopped" // valid: "always", "unless-stopped", "on-failure"
container_restart_policy: unless-stopped

# Enables the "watchtower" container to automatically download and apply container updates // default: "yes"
container_enable_auto_updates: yes

# The cron-style schedule for the watchtower container to check for updates in UTC time // default: "0 0 9 * * *"
container_auto_update_schedule: "0 0 1 * * *"

# Will stop and remove containers that you disable within the container map (defined below) // default: "yes"
container_remove_orphans: yes

# The timezone to use for the containers // default: "America/New_York"
container_timezone: Europe/Paris

# User and Group ID's to use for the running processes in the containers (may cause or be the cause of permissions issues)
#  default: "1234"
container_uid: 1234
container_gid: 1234

# This will download all of the containers before attempting to start them // default: "yes"
container_pull_images_first: yes

# This will expose each containers individual ports on the host (check the README for more info on which ports map to which containers) // default: "no"
# If you disable traefik within the container map, the playbook will automatically override this setting and expose the ports
container_expose_ports: no
