### SSL and Traefik settings
traefik_container_tag: v2.10.1

# Enables or Disables SSL wildcard certificate generation // default: "no"
traefik_ssl_enabled: yes

# This option implements a number of additional security features for Traefik, such as:
# * Disable TLS1.0
traefik_security_hardening: yes # default: no

# Whether to use the staging/testing URL or production URL // default: "yes"
# If SSL is enabled and this is set to yes, check to make sure the generated certificate is issued from the "STAGING" certificate authority before changing this to "no"
traefik_ssl_use_letsencrypt_staging_url: yes

# SANs (Subject Alternative Names) to also provision certificates for
# By default, this will create a "wildcard" (*) certificate
# If you wish to create a certificate for another subdomain (such as '*.public'), you can add them here
traefik_ssl_sans: [
  '*.{{ hms_docker_domain }}',
]

# The DNS provider to use for SSL generation, check this for supported providers: https://doc.traefik.io/traefik/https/acme/#providers
traefik_ssl_dns_provider_code: "ovh"

# The DNS zone to use for SSL generation, this will use the domain defined above // default: "{{ hms_docker_domain }}"
traefik_ssl_dns_provider_zone: "{{ hms_docker_domain }}"

# The environment variables for your DNS provider found at the provider link above
# This is an example if using Cloudflare
traefik_ssl_dns_provider_environment_vars:
  {
    "OVH_ENDPOINT": "ovh-eu",
    "OVH_APPLICATION_KEY": "",
    "OVH_APPLICATION_SECRET": "",
    "OVH_CONSUMER_KEY": ""
  }

# The DNS servers to use when generating your SSL certificate, recommended to set to your DNS providers servers
traefik_ssl_dns_resolver_1: "213.251.188.146"
traefik_ssl_dns_resolver_2: "213.251.128.146"

# Required for Let's Encrypt, the email address to use when generating your SSL certificate
traefik_ssl_letsencrypt_email: ""


# The Traefik log level, helpful for troubleshooting SSL issues // default: "INFO"
traefik_log_level: "INFO"

# Enable or disable to check if all possible Traefik routes are available (requires all FQDN DNS records to be valid) // default: "no"
traefik_verify_endpoints: yes

# Enable or disable full request logging
traefik_enable_access_logs: no

# The Traefik allow-list for all containers EXCEPT the Overseerr container, the Overseerr container allows ALL IP's by default
# This allows all RFC1918 addresses by default, you can change this to further restrict or allow greater access
traefik_subnet_allow_list: "{{ hms_docker_network_subnet }}, 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16"
